### ISSUE TITLE
Skeleton for Sprint boot chatbot 

### ISSUE THREAD

**Issue by IniZio** [khwang0/2017F-COMP3111#4]
Repo address: [Line Chatbot Skeleton](https://github.com/IniZio/com.comp3111.chatbot-skeleton)

- Instructions for developing on localhost
- Integration with Travis-CI for checking
- Integration with Heroku for deployment

**Comment by khwang0** [comment]
Thanks for raising an issue here. I guess that repo is to make use of `ngrok` to tackle NAT/firewall for localhost server. But the code does not look like it support any communication between LINE Server yet.

**Comment by IniZio** [comment]
Just to avoid being considered as plagiarism. It imports the linebot sdk for convenience of use the Line messaging API
